version: '3'

networks:
  default:
    driver: bridge

services:
  web:
    image: cosmtrek/air
    working_dir: /src
    env_file:
      - meddle.env
    ports: 
      - 8081:8080
    depends_on:
      - "db"
    volumes:
      - ./:/src
      - gomodules:/go/pkg/mod

  db:
    image: postgres
    container_name: meddle_db
    environment:
      POSTGRES_DB: meddle
      POSTGRES_PASSWORD: pleasedontshare
    ports:
      - 5434:5432

volumes:
  gomodules:
