swagger: '2.0'
info:
  description: >-
    This is meddle, an app that keeps track of medications with notification
    feature.
  version: 3.0.0
  title: Meddle
  contact:
    email: info@decagonhq.com
host: meddle.herokuapp.com
basePath: /api/v1
schemes:
  - https
  - http
paths:
  /auth/signup:
    post:
      tags:
        - user
      summary: Create user
      description: This creates a new user entry in the data.
      operationId: createUser
      produces:
        - application/json
      parameters:
        - in: body
          name: Signup
          description: Created user object
          required: true
          schema:
            $ref: '#/definitions/User'
      responses:
        '200':
          description: Created medication successfully
          schema:
            $ref: '#/definitions/SignupResponse'
  /auth/login:
    post:
      tags:
        - user
      summary: Logs user into the system
      description: ''
      operationId: loginUser
      produces:
        - application/json
      parameters:
        - in: body
          name: user
          description: login user to the system
          required: true
          schema:
            $ref: '#/definitions/UserRequest'
      responses:
        '200':
          description: successful operation
          schema:
            $ref: '#/definitions/LoginResponse'
          headers:
            X-Rate-Limit:
              type: integer
              format: int32
              description: calls per hour allowed by the user
            X-Expires-After:
              type: string
              format: date-time
              description: date in UTC when token expires
        '400':
          description: Invalid username/password supplied
  /logout:
    get:
      tags:
        - user
      summary: Logs out current logged in user session
      description: ''
      operationId: logoutUser
      produces:
        - application/json
      parameters: []
      responses:
        default:
          description: successful operation
  /user/{email}:
    get:
      tags:
        - user
      summary: Get user by user email
      description: ''
      operationId: getUserByEmail
      produces:
        - application/json
      parameters:
        - name: email
          in: path
          description: 'The name that needs to be fetched. Use user1 for testing. '
          required: true
          type: string
      responses:
        '200':
          description: successful operation
          schema:
            $ref: '#/definitions/User'
        '400':
          description: Invalid username supplied
        '404':
          description: User not found
    put:
      tags:
        - user
      summary: Updated user
      description: This can only be done by the logged in user.
      operationId: updateUser
      produces:
        - application/json
      parameters:
        - name: email
          in: path
          description: name that need to be updated
          required: true
          type: string
        - in: body
          name: body
          description: Updated user object
          required: true
          schema:
            $ref: '#/definitions/User'
      responses:
        '400':
          description: Invalid user supplied
        '404':
          description: User not found
    delete:
      tags:
        - user
      summary: Delete user
      description: This can only be done by the logged in user.
      operationId: deleteUser
      produces:
        - application/json
      parameters:
        - name: email
          in: path
          description: The email that needs to be deleted
          required: true
          type: string
      responses:
        '400':
          description: Invalid email supplied
        '404':
          description: User not found
  /verifyEmail/{token}:
    get:
      tags:
        - user
      summary: Verify users email
      description: ''
      operationId: veryfyEmail
      produces:
        - application/json
      parameters:
        - name: token
          in: path
          description: 'Gets the token sent by signup. '
          required: true
          type: string
      responses:
        '200':
          description: successfully verified user
          schema:
            $ref: '#/definitions/User'
        '400':
          description: Invalid token supplied
        '404':
          description: Token is not valid
  /user/medications:
    post:
      tags:
        - medication
      summary: Create medication
      description: This creates a new medication entry in the data.
      operationId: createMedication
      produces:
        - application/json
      parameters:
        - in: body
          name: medication
          description: medication to add the system
          required: true
          schema:
            $ref: '#/definitions/Medication'
      responses:
        '200':
          description: Created medication successfully
          schema:
            $ref: '#/definitions/MedicationResponse'
        '400':
          description: Bad request from user
        '403':
          description: Forbidden user
        '500':
          description: Internal server error
  /user/medications/{id}:
    get:
      tags:
        - medication
      summary: Get user medication by id and userid
      description: ''
      operationId: getUserById
      produces:
        - application/json
      parameters:
        - name: id
          in: path
          description: 'The name that needs to be fetched. Use user1 for testing. '
          required: true
          type: string
      responses:
        '200':
          description: retrieved medications successfully
          schema:
            $ref: '#/definitions/Medication'
        '500':
          description: Internal server error
        '404':
          description: Medication not found
  /user/medications/next:
    get:
      tags:
        - medication
      summary: Get next medication for user
      description: This gets next medication related to a logged in user.
      operationId: getNextMedication
      produces:
        - application/json
      responses:
        '200':
          description: get next medications successful
          schema:
            $ref: '#/definitions/MedicationResponse'
        '403':
          description: Forbidden user
        '500':
          description: Internal server error
securityDefinitions:
  bearerAuth:
    type: apiKey
    name: Authorization
    in: header
definitions:
  UserRequest:
    type: object
    properties:
      email:
        type: string
        format: email
      password:
        type: string
        format: password
    xml:
      name: UserRequest
  UserResponse:
    type: object
    properties:
      id:
        type: integer
        format: uint
        example: 1
      created_at:
        type: string
        format: date-time
      updated_at:
        type: string
        format: date-time
      deleted_at:
        type: string
        format: date-time
      name:
        type: string
        format: string
        example: "Ken"
      email:
        type: string
        format: email
        example: "ken@gmail.com"
      password:
        type: string
        format: password
        example: "password"
      phone_number:
        type: string
        format: phone
        example: "090834343"
    xml:
      name: UserResponse
  SignupResponse:
    type: object
    properties:
      data:
        $ref: '#/definitions/UserResponse'
      errors:
        type: string
        example: ""
      message:
        type: string
        example: "user created successfully"
      status:
        type: string
        example: "Created"
  LoginResponse:
    type: object
    properties:
      data:
        $ref: '#/definitions/loginResponseData'
      errors:
        type: string
        example: ""
      message:
        type: string
        example: "user created successfully"
      status:
        type: string
        example: "Created"
  User:
    type: object
    properties:
      name:
        type: string
      phone_number:
        type: string
      email:
        type: string
      password:
        type: string
    xml:
      name: User
  loginResponseData:
    type: object
    properties:
      id:
        type: integer
        example: 1
      name:
        type: string
        example: "Ken"
      phone_number:
        type: string
        example: "09043556"
      email:
        type: string
        example: "ken@gmail.com"
      accessToken:
        type: string
        example: "Rbhfwi2PUXndOWVlUpsy0"
  Medication:
    type: object
    properties:
      name:
        type: string
        example: "paracetamol"
      dosage:
        type: integer
        format: int
        example: 2
        description: number of medication (dose) to take
      time_interval:
        type: integer
        format: int
        example: 8
        description: the next time-interval of hours to take your medication
      medication_start_date:
        type: string
        format: date-time
        description: day for starting medication
      duration:
        type: integer
        format: int
        example: 7
        description: number of days to take the medication
      medication_prescribed_by:
        type: string
        example: "Dr Tolu"
      medication_stop_date:
        type: string
        format: date-time
        description: expected date to finish medication
      medication_start_time:
        type: string
        format: date-time
        description: expected day to start medication
      purpose_of_medication:
        type: string
        example: "malaria treatment"
    xml:
      name: Medication
  MedicationResponse:
    type: object
    properties:
      id:
        type: integer
        format: uint
        example: 1
      name:
        type: string
        example: "paracetamol"
      dosage:
        type: integer
        format: int
        example: 2
      time_interval:
        type: integer
        example: 8
        description: the next time-interval of hours to take your medication
      medication_start_date:
        type: string
        format: date-time
        description: day for starting medication
      duration:
        type: integer
        format: int
        example: 7
        description: number of days to take the medication
      medication_prescribed_by:
        type: string
        example: "Dr Tolu"
      medication_stop_date:
        type: string
        format: date-time
        description: expected date to finish medication
      medication_start_time:
        type: string
        format: date-time
        description: expected day to start medication
      next_dosage_time:
        type: string
        format: date-time
        description: next time to take of medication (dose)
      purpose_of_medication:
        type: string
        example: "malaria treatment"
      user_id:
        type: integer
        format: uint
        example: 2
        description: owner of medication id
      created_at:
        type: string
        format: date-time
      updated_at:
        type: string
        format: date-time
    xml:
      name: MedicationResponse