name: Go

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18

      - name: Build
        run: go build -v ./...
      - name: Test
        run: |
          export MEDDLE_JWT_SECRET=veryLONGsecret
          go install github.com/golang/mock/mockgen@v1.6.0
          make test
      - uses: readmeio/rdme@7.3.0
        with:
          rdme: openapi openapi/openapi.yml --key=${{secrets.README_API_KEY}} --id=${{secrets.README_API_DEFINITION_ID}}
      - name: Deploy
        run: |
          mkdir ~/.ssh
          touch ~/.ssh/known_hosts
          ssh-keygen -R ec2-3-143-47-141.us-east-2.compute.amazonaws.com
          echo -n "${{secrets.MEDDLE_AWS_KEY}}" > meddle.pem

          GOOS=linux GOARCH=amd64 go build -o meddle .
          rsync -auv -e "ssh -i meddle.pem" ./config/meddle-e0182-firebase-adminsdk-jzzg4-6f1bd5437b.json ubuntu@ec2-3-143-47-141.us-east-2.compute.amazonaws.com:/home/ubuntu/server/
          rsync -auv -e "ssh -i meddle.pem" ./server/templates/* ubuntu@ec2-3-143-47-141.us-east-2.compute.amazonaws.com:/home/ubuntu/server/templates/
          rsync -auv -e "ssh -i meddle.pem" ./meddle ubuntu@ec2-3-143-47-141.us-east-2.compute.amazonaws.com:/home/ubuntu/
          ssh -i meddle.pem ubuntu@ec2-3-143-47-141.us-east-2.compute.amazonaws.com "sudo systemctl restart meddle.service"
          sleep 3
          ssh -i meddle.pem ubuntu@ec2-3-143-47-141.us-east-2.compute.amazonaws.com "sudo systemctl status meddle.service"

